<?php

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function course_theme() {
  return [
    'course' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for course templates.
 *
 * Default template: course.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the course information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_course(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
